//
// This source file is from part of poco library
//
// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#pragma once

// from POCO 1.3 Event.h

#include "nit/nit.h"

#if defined(NIT_THREAD_WIN32)
#	include "nit/async/EventSemaphore_win32.h"

#elif defined(NIT_THREAD_POSIX)
#	include "nit/async/EventSemaphore_posix.h"
#endif

NS_NIT_BEGIN;

////////////////////////////////////////////////////////////////////////////////

class NIT_API EventSemaphore: private EventSemaphoreImpl
	/// An EventSemaphore is a synchronization object that
	/// allows one thread to signal one or more
	/// other threads that a certain event
	/// has happened. (same as Event Object on Win32)
	/// Usually, one thread signals a ready event,
	/// while one or more other threads wait
	/// for a ready event to become signalled.
{
public:
	EventSemaphore(bool autoReset = true);
		/// Creates the EventSemaphore. If autoReset is true,
		/// the event is automatically reset after
		/// a wait() successfully returns.
		
	~EventSemaphore();
		/// Destroys the EventSemaphore.

	void set();
		/// Signals the ready event. If autoReset is true,
		/// only one thread waiting for the event 
		/// can resume execution.
		/// If autoReset is false, all waiting threads
		/// can resume execution.

	void wait();
		/// Waits for the ready event to become signalled.

	void wait(long milliseconds);
		/// Waits for the ready event to become signalled.
		/// Throws a TimeoutException if the event
		/// does not become signalled within the specified
		/// time interval.

	bool tryWait(long milliseconds);
		/// Waits for the ready event to become signalled.
		/// Returns true if the event
		/// became signalled within the specified
		/// time interval, false otherwise.

	void reset();
		/// Resets the EventSemaphore to unsignalled state.
	
private:
	EventSemaphore(const EventSemaphore&);
	EventSemaphore& operator = (const EventSemaphore&);
};


//
// inlines
//
inline void EventSemaphore::set()
{
	setImpl();
}


inline void EventSemaphore::wait()
{
	waitImpl();
}


inline void EventSemaphore::wait(long milliseconds)
{
	if (!waitImpl(milliseconds))
		throw TimeoutException();
}


inline bool EventSemaphore::tryWait(long milliseconds)
{
	return waitImpl(milliseconds);
}


inline void EventSemaphore::reset()
{
	resetImpl();
}

////////////////////////////////////////////////////////////////////////////////

NS_NIT_END;
